Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Enabled: false
  
Lint/ScriptPermission:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
 Enabled: false

Metrics/MethodLength:
 Enabled: false

Metrics/CyclomaticComplexity:
 Enabled: false
    